### ISSUE TITLE
Issue with parsing Messenger chat logs

### ISSUE THREAD

**Issue by manankalra** [MasterScrat/Chatistics#1]
After downloading the archive created by Facebook, we get chats in a directory named **messages** and **messages.htm** internally links to them. Even after adding the _messages_ directory to the raw folder, no messages are being parsed. Need a little help here.

![issue](https://user-images.githubusercontent.com/12759088/31469032-dc0544e4-aefd-11e7-9140-56565f068570.png)

**Comment by MasterScrat** [comment]
Hello @manankalra, indeed the export format changed for Messenger chat logs. 

Commit #04c1e0bbbf33fd358f67eb5ec6d0bca13e686b0c should solve your issue, let me know if you still have problems.

Note that you now have to move the whole `messages` directory in the `raw` folder.
