### ISSUE TITLE
WhatsApp support?

### ISSUE THREAD

**Issue by MasterScrat** [MasterScrat/Chatistics#13]
Subscribe/comment to this issue if you would be interested in support of this platform.

**Comment by MasterScrat** [comment]
It doesn't seem possible to do bulk export from the WhatsApp app, you can only email conversations one by one. And all the "backup" app I see ask you to pay to do their job.

Any idea of a good solution?

**Comment by hundredrab** [comment]
I'd think this actually works better as far as WhatsApp is concerned. You might want to analyze only a few conversations at a time. So far as that goes, maybe consider parsing only the available texts?

**Comment by MasterScrat** [comment]
Implemented in new version!
