### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by yatharth96** [MasterScrat/Chatistics#21]
Having ModuleNotFoundError while running the command 

`python parsers/messenger.py --own-name "John Doe"`

There's __ init __.py in _parsers_ subdirectory, still facing this issue.
 
`Traceback (most recent call last):
  File "parsers/messenger.py", line 11, in <module>
    from parsers import log
ModuleNotFoundError: No module named 'parsers'`

**Comment by MasterScrat** [comment]
There’s the solution for this in the readme. 

But I agree it’s not ideal. So let’s leave this issue open until we find a cleaner way to handle it.

**Comment by hundredrab** [comment]
Opened a PR to fix this. Slightly ugly, but it works.

**Comment by MasterScrat** [comment]
Fixed in new version!

Sorry @hundredrab, I was not able to merge your PR in the interval.
