### ISSUE TITLE
Module dependencies

### ISSUE THREAD

**Issue by farisachugthai** [MasterScrat/Chatistics#26]
Hey there, 

So I've cloned the project a few times before, and even though I've gotten it to work, Chatistics doesn't work out of the box for me. My environment variables were already set, but LXML was giving me trouble, as where some dependencies that aren't listed in the requirements.txt. I noticed that there's a section for libxml in the README, but I just wanted to ask if you guys were taking any pull requests to add some fallbacks in case certain modules aren't already installed. Thanks!

**Comment by MasterScrat** [comment]
Hey @farisachugthai, yes I would happily accept pull requests that would make the initial setup smoother!

**Comment by farisachugthai** [comment]
Hey so I've spent a few days playing around with a LOT of the code. Hahaha I think I ended up falling down a rabbit hole, but in the process managed to identify and solve quite a few of the problems that I was initially having. 

Full disclosure, this is my first contribution to an open source project, a project on GitHub and it's actually my first contribution of any kind of code ever. So I suppose be warned? But I tried to be as clear as possible in my work. 

So before I push anything, I wanted to ask if i could also add in a file for people using conda to manage py envs. The requirements as they are currently listed are flagged as incompatible by Anaconda, and I was hoping to throw in an alternative solution.

**Comment by MasterScrat** [comment]
Hey @farisachugthai sure make a PR with everything you have and we can discuss from there

**Comment by hundredrab** [comment]
Hey, @MasterScrat. Couldn't help but notice that a lot of these issues would be easily resolved if the project could be packaged and hosted somewhere like PyPi. An added advantage of this would be easy installation using pip/pip3. If you think this is a good idea, could I add in a PR?

**Comment by MasterScrat** [comment]
Yes sure that would be great! :D

**Comment by MasterScrat** [comment]
Let's continue this discussion in #26.
