### ISSUE TITLE
Problem activating Chatistics shell

### ISSUE THREAD

**Issue by willem-h** [MasterScrat/Chatistics#52]
I had it working on the 17th of January but I updated the master branch today and now `conda activate chatistics` fails with:

```
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.
```

Before trying this I deleted the existing environment out of `~/anaconda/envs/` and ran `conda env create -f environment.yml`

I also updated to Catalina in the meantime if that makes any difference.

Any ideas as to how I can get this working?

Edited to remove `env` from `conda activate chatistics`.

**Comment by mar-muel** [comment]
Hi @willem-h ! The syntax of conda is unfortunately a bit confusing.

It is `conda env create -f environment.yml` but then `conda activate <env name>` (without the `env`). Hope this helps!

**Comment by willem-h** [comment]
Hi @mar-muel, thanks for your response! The `env` is a typo 🤦‍♂  I checked again to make sure and I get the same error that I posted above.

Any more ideas?

**Comment by mar-muel** [comment]
I saw this error with someone who used it in JupyterLab/inside a notebook. Is it possible you are not running this in a terminal?

**Comment by willem-h** [comment]
@mar-muel No, I'm running it in iTerm with a zsh shell.

**Comment by willem-h** [comment]
I got this working 🎉

From the error state above:
1. `conda init zsh`
2. Close and reopen terminal
3. `conda activate chatistics`
