### ISSUE TITLE
WhatsApp parse error

### ISSUE THREAD

**Issue by cameronweibel** [MasterScrat/Chatistics#53]
I have exported the WhatsApp chat from a single conversation, and after running `python parse.py whatsapp --own-name "firstname lastname"` each row in the "senderName" column has a prefix of AM/PM (from the timestamp), e.g. "AM - _firstname_ _lastname_" or "PM - _firstname_ _lastname_". This leads to errors in visualization, etc. ![https://i.imgur.com/apYzehQ.jpg](https://i.imgur.com/apYzehQ.jpg)

Here are a few lines from the WhatsApp export for reproducibility:

9/18/18, 2:45 PM - firstname1 lastname1: I'm sorry! I was talking to people throughout the lunch break!
9/18/18, 4:24 PM - firstname2 lastname2: I'm glad it is going so well!
9/18/18, 4:25 PM - firstname2 lastname2: Here's a quick outtake from the filming
9/18/18, 4:25 PM - firstname2 lastname2: \<Media omitted\>

**Comment by MasterScrat** [comment]
Just merged PR #54 from @manueth which should solve the problem - let us know if that works with your dataset!

**Comment by cameronweibel** [comment]
It works now, thanks.
