### ISSUE TITLE
"ValueError: ordinal must be >= 1" when parsing Messenger chat logs

### ISSUE THREAD

**Issue by arosen93** [MasterScrat/Chatistics#6]
I still haven't had success yet with parsing the FB messages. One issues was that `timestamp = pd.to_datetime(content, format='%A, %B %d, %Y at %H:%M%p', exact=False).strftime("%s")` had an invalid format string. I changed it to "%S" since I assume that's what you meant. However, I now get the following issue when running `analyse.py`.

```
Traceback (most recent call last):
  File "analyse.py", line 90, in <module>
    print(plot)
  File "C:\Users\asros\Anaconda3\envs\py2\lib\site-packages\ggplot\ggplot.py", line 116, in __repr__
    self.make()
  File "C:\Users\asros\Anaconda3\envs\py2\lib\site-packages\ggplot\ggplot.py", line 641, in make
    self.apply_axis_labels()
  File "C:\Users\asros\Anaconda3\envs\py2\lib\site-packages\ggplot\ggplot.py", line 231, in apply_axis_labels
    labels.append(self.xtick_formatter(label_text))
  File "C:\Users\asros\Anaconda3\envs\py2\lib\site-packages\matplotlib\dates.py", line 542, in __call__
    dt = num2date(x, self.tz)
  File "C:\Users\asros\Anaconda3\envs\py2\lib\site-packages\matplotlib\dates.py", line 445, in num2date
    return _from_ordinalf(x, tz)
  File "C:\Users\asros\Anaconda3\envs\py2\lib\site-packages\matplotlib\dates.py", line 260, in _from_ordinalf
    dt = datetime.datetime.fromordinal(ix).replace(tzinfo=UTC)
ValueError: ordinal must be >= 1
```

**Comment by acbart** [comment]
I changed it to .timestamp instead of stftime('%S') (which I believe would be the number of seconds instead of a timestamp). My rough guess for that error you're getting is that any chat messages sent at exactly the minute mark (seconds=0) is causing a timestamp of 0 seconds, which crashes that line of code that tries to work with datetimes.

    timestamp = pd.to_datetime(content, format='%A, %B %d, %Y at %H:%M%p', exact=False).timestamp()

**Comment by arosen93** [comment]
That makes sense. I have hundreds of thousands of messages, so I can almost guarantee there will be some messages exactly at the minute mark. I'll just fuzz the data a bit when that happens. Thanks for the insight. I'm not used to working with datetime.

**Comment by acbart** [comment]
I don't think fuzzing will do what you want - you need to be generating timestamps, not the seconds. Have you tried using the line of code I suggested?

**Comment by arosen93** [comment]
Completely misread your message -- apologies about that. I tried substituting in your line of code into `parse_messenger.py` but get:

```
C:\Users\asros\Anaconda3\envs\py2\lib\site-packages\pandas\core\ops.py:816: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = getattr(x, name)(y)
Traceback (most recent call last):
  File "parse_messenger.py", line 124, in <module>
    df['datetime'] = df[df["timestamp"] != ""]['timestamp'].apply(
  File "C:\Users\asros\Anaconda3\envs\py2\lib\site-packages\pandas\core\ops.py", line 879, in wrapper
    res = na_op(values, other)
  File "C:\Users\asros\Anaconda3\envs\py2\lib\site-packages\pandas\core\ops.py", line 818, in na_op
    raise TypeError("invalid type comparison")
TypeError: invalid type comparison
```

**Comment by acbart** [comment]
I fixed that by changing line 124 to this:

    # Filter out null timestamps
    non_blank_timestamps = ~df.timestamp.isnull()
    df['datetime'] = df[non_blank_timestamps]['timestamp'].apply(ordinate)

I think that's an adequate fix. The problem was that the timestamp column is float (or at least should be), and apparently you can't just check to see if it's empty string. I just checked if it was null. There's probably a different check to be making instead, but I don't think I have any invalid timestamps so I can't test it out.

**Comment by arosen93** [comment]
I see. What did you define `ordinate` as? It's been a while since I've worked with pandas.

**Comment by acbart** [comment]
Oops, sorry, meant to include that too:

    ordinate = lambda x: datetime.datetime.fromtimestamp(float(x)).toordinal()
    # Filter out null timestamps
    non_blank_timestamps = ~df.timestamp.isnull()
    df['datetime'] = df[non_blank_timestamps]['timestamp'].apply(ordinate)

**Comment by arosen93** [comment]
That worked perfectly! Thank you!

**Comment by MasterScrat** [comment]
Does this solution also work with Python 2? If yes can you please make a Pull Request?

**Comment by arosen93** [comment]
I've confirmed that it does work for Python 2 and submitted a PR.

**Comment by MasterScrat** [comment]
Let's wait until it's pushed to `master` until we close this issue...

**Comment by MasterScrat** [comment]
@arosen93 with what version of Python 2 did you test? `.timestamp()` is failing for me with Python 2.7.13:

> Traceback (most recent call last):
>   File "parse_messenger.py", line 77, in <module>
>     timestamp = pd.to_datetime(content, infer_datetime_format=True).timestamp()
> AttributeError: 'Timestamp' object has no attribute 'timestamp'

I'm afraid it was introduced with Python 3.

Also I don't find your Pull Request?
