### ISSUE TITLE
ValueError: time data 'Sunday, 11 March 2012 at 15:11 UTC+01' does not match format '%A, %B %d, %Y at %H:%M%p' (search)

### ISSUE THREAD

**Issue by edvinli** [MasterScrat/Chatistics#7]
I get a problem when trying to parse the facebook messenger files. I get 
`  File "parse_messenger.py", line 76, in <module>
    timestamp = pd.to_datetime(content, format='%A, %B %d, %Y at %H:%M%p', exact=False).strftime("%s")` 

and

 `'ValueError: time data 'Sunday, 11 March 2012 at 15:11 UTC+01' does not match format '%A, %B %d, %Y at %H:%M%p' (search)`

Is this perhaps due to different time stamps formats or that they are older?

**Comment by MasterScrat** [comment]
It looks like Facebook isn't consistent with the date format it uses, some people get 24h format and others 12h format.

If you replace line 76 with this does it work?

`timestamp = pd.to_datetime(content, infer_datetime_format=True).strftime("%s")`

**Comment by edvinli** [comment]
@MasterScrat Perfect! The script is now running. Will see if I am amble to analyse the results when all data has been generated. Thanks!

**Comment by edvinli** [comment]
@MasterScrat Now it works good. But I have two questions:

1) I don't get the histogram to stack, as in the example in the readme. I get that the histogram when plotting my top 10 are added behind and in front of each other instead of stacking. Any idea as to why?

2) The density plot does not fill, I haven't figured out why that is.

3) Is it possible to plot density or histogram plots for two or more persons by specifying them within the -filterConversation flag?

**Comment by MasterScrat** [comment]
Ok glad it works! but unfortunately `infer_datetime_format` makes the parsing 10x slower...

Good questions, but let's keep one problem per issue so we can keep track of what's happening:

Problems with ggplot: Histograms don't stack, density plots don't fill #8

Improve filtering options #9
